/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SellerSalesRouteImport } from './routes/seller.sales'
import { Route as SellerProfileRouteImport } from './routes/seller.profile'
import { Route as SellerPerformanceRouteImport } from './routes/seller.performance'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerNotificationsRouteImport } from './routes/seller.notifications'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCollectionsRouteImport } from './routes/admin.collections'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as SiteTrackRouteImport } from './routes/_site.track'
import { Route as SiteTermsRouteImport } from './routes/_site.terms'
import { Route as SiteSearchRouteImport } from './routes/_site.search'
import { Route as SiteReturnsRouteImport } from './routes/_site.returns'
import { Route as SiteProductsRouteImport } from './routes/_site.products'
import { Route as SitePrivacyRouteImport } from './routes/_site.privacy'
import { Route as SiteFaqRouteImport } from './routes/_site.faq'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteCheckoutRouteImport } from './routes/_site.checkout'
import { Route as SiteCartRouteImport } from './routes/_site.cart'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteProductSlugRouteImport } from './routes/_site.product.$slug'
import { Route as SiteOrderConfirmationIdRouteImport } from './routes/_site.order-confirmation.$id'
import { Route as SiteCollectionSlugRouteImport } from './routes/_site.collection.$slug'
import { Route as SiteCategorySlugRouteImport } from './routes/_site.category.$slug'

const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SellerSalesRoute = SellerSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProfileRoute = SellerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SellerRoute,
} as any)
const SellerPerformanceRoute = SellerPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerNotificationsRoute = SellerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SellerRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const SiteTrackRoute = SiteTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSearchRoute = SiteSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => SiteRoute,
} as any)
const SiteReturnsRoute = SiteReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductsRoute = SiteProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCheckoutRoute = SiteCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCartRoute = SiteCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductSlugRoute = SiteProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOrderConfirmationIdRoute = SiteOrderConfirmationIdRouteImport.update({
  id: '/order-confirmation/$id',
  path: '/order-confirmation/$id',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCollectionSlugRoute = SiteCollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCategorySlugRoute = SiteCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/seller': typeof SellerRouteWithChildren
  '/about': typeof SiteAboutRoute
  '/cart': typeof SiteCartRoute
  '/checkout': typeof SiteCheckoutRoute
  '/contact': typeof SiteContactRoute
  '/faq': typeof SiteFaqRoute
  '/privacy': typeof SitePrivacyRoute
  '/products': typeof SiteProductsRoute
  '/returns': typeof SiteReturnsRoute
  '/search': typeof SiteSearchRoute
  '/terms': typeof SiteTermsRoute
  '/track': typeof SiteTrackRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/seller/notifications': typeof SellerNotificationsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/performance': typeof SellerPerformanceRoute
  '/seller/profile': typeof SellerProfileRoute
  '/seller/sales': typeof SellerSalesRoute
  '/admin/': typeof AdminIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/category/$slug': typeof SiteCategorySlugRoute
  '/collection/$slug': typeof SiteCollectionSlugRoute
  '/order-confirmation/$id': typeof SiteOrderConfirmationIdRoute
  '/product/$slug': typeof SiteProductSlugRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/cart': typeof SiteCartRoute
  '/checkout': typeof SiteCheckoutRoute
  '/contact': typeof SiteContactRoute
  '/faq': typeof SiteFaqRoute
  '/privacy': typeof SitePrivacyRoute
  '/products': typeof SiteProductsRoute
  '/returns': typeof SiteReturnsRoute
  '/search': typeof SiteSearchRoute
  '/terms': typeof SiteTermsRoute
  '/track': typeof SiteTrackRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/seller/notifications': typeof SellerNotificationsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/performance': typeof SellerPerformanceRoute
  '/seller/profile': typeof SellerProfileRoute
  '/seller/sales': typeof SellerSalesRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/seller': typeof SellerIndexRoute
  '/category/$slug': typeof SiteCategorySlugRoute
  '/collection/$slug': typeof SiteCollectionSlugRoute
  '/order-confirmation/$id': typeof SiteOrderConfirmationIdRoute
  '/product/$slug': typeof SiteProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/seller': typeof SellerRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/cart': typeof SiteCartRoute
  '/_site/checkout': typeof SiteCheckoutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/products': typeof SiteProductsRoute
  '/_site/returns': typeof SiteReturnsRoute
  '/_site/search': typeof SiteSearchRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_site/track': typeof SiteTrackRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/seller/notifications': typeof SellerNotificationsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/performance': typeof SellerPerformanceRoute
  '/seller/profile': typeof SellerProfileRoute
  '/seller/sales': typeof SellerSalesRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/_site/category/$slug': typeof SiteCategorySlugRoute
  '/_site/collection/$slug': typeof SiteCollectionSlugRoute
  '/_site/order-confirmation/$id': typeof SiteOrderConfirmationIdRoute
  '/_site/product/$slug': typeof SiteProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/seller'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/products'
    | '/returns'
    | '/search'
    | '/terms'
    | '/track'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/sellers'
    | '/admin/settings'
    | '/seller/notifications'
    | '/seller/orders'
    | '/seller/performance'
    | '/seller/profile'
    | '/seller/sales'
    | '/admin/'
    | '/seller/'
    | '/category/$slug'
    | '/collection/$slug'
    | '/order-confirmation/$id'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/products'
    | '/returns'
    | '/search'
    | '/terms'
    | '/track'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/sellers'
    | '/admin/settings'
    | '/seller/notifications'
    | '/seller/orders'
    | '/seller/performance'
    | '/seller/profile'
    | '/seller/sales'
    | '/'
    | '/admin'
    | '/seller'
    | '/category/$slug'
    | '/collection/$slug'
    | '/order-confirmation/$id'
    | '/product/$slug'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/seller'
    | '/_site/about'
    | '/_site/cart'
    | '/_site/checkout'
    | '/_site/contact'
    | '/_site/faq'
    | '/_site/privacy'
    | '/_site/products'
    | '/_site/returns'
    | '/_site/search'
    | '/_site/terms'
    | '/_site/track'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/sellers'
    | '/admin/settings'
    | '/seller/notifications'
    | '/seller/orders'
    | '/seller/performance'
    | '/seller/profile'
    | '/seller/sales'
    | '/_site/'
    | '/admin/'
    | '/seller/'
    | '/_site/category/$slug'
    | '/_site/collection/$slug'
    | '/_site/order-confirmation/$id'
    | '/_site/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  SellerRoute: typeof SellerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/seller/sales': {
      id: '/seller/sales'
      path: '/sales'
      fullPath: '/seller/sales'
      preLoaderRoute: typeof SellerSalesRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/profile': {
      id: '/seller/profile'
      path: '/profile'
      fullPath: '/seller/profile'
      preLoaderRoute: typeof SellerProfileRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/performance': {
      id: '/seller/performance'
      path: '/performance'
      fullPath: '/seller/performance'
      preLoaderRoute: typeof SellerPerformanceRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/notifications': {
      id: '/seller/notifications'
      path: '/notifications'
      fullPath: '/seller/notifications'
      preLoaderRoute: typeof SellerNotificationsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/track': {
      id: '/_site/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof SiteTrackRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/search': {
      id: '/_site/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SiteSearchRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/returns': {
      id: '/_site/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof SiteReturnsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/products': {
      id: '/_site/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof SiteProductsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/checkout': {
      id: '/_site/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof SiteCheckoutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cart': {
      id: '/_site/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof SiteCartRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/product/$slug': {
      id: '/_site/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof SiteProductSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/order-confirmation/$id': {
      id: '/_site/order-confirmation/$id'
      path: '/order-confirmation/$id'
      fullPath: '/order-confirmation/$id'
      preLoaderRoute: typeof SiteOrderConfirmationIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/collection/$slug': {
      id: '/_site/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof SiteCollectionSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/category/$slug': {
      id: '/_site/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof SiteCategorySlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteCartRoute: typeof SiteCartRoute
  SiteCheckoutRoute: typeof SiteCheckoutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteProductsRoute: typeof SiteProductsRoute
  SiteReturnsRoute: typeof SiteReturnsRoute
  SiteSearchRoute: typeof SiteSearchRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteTrackRoute: typeof SiteTrackRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteCategorySlugRoute: typeof SiteCategorySlugRoute
  SiteCollectionSlugRoute: typeof SiteCollectionSlugRoute
  SiteOrderConfirmationIdRoute: typeof SiteOrderConfirmationIdRoute
  SiteProductSlugRoute: typeof SiteProductSlugRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteCartRoute: SiteCartRoute,
  SiteCheckoutRoute: SiteCheckoutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteFaqRoute: SiteFaqRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteProductsRoute: SiteProductsRoute,
  SiteReturnsRoute: SiteReturnsRoute,
  SiteSearchRoute: SiteSearchRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteTrackRoute: SiteTrackRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteCategorySlugRoute: SiteCategorySlugRoute,
  SiteCollectionSlugRoute: SiteCollectionSlugRoute,
  SiteOrderConfirmationIdRoute: SiteOrderConfirmationIdRoute,
  SiteProductSlugRoute: SiteProductSlugRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCollectionsRoute: typeof AdminCollectionsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCollectionsRoute: AdminCollectionsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SellerRouteChildren {
  SellerNotificationsRoute: typeof SellerNotificationsRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerPerformanceRoute: typeof SellerPerformanceRoute
  SellerProfileRoute: typeof SellerProfileRoute
  SellerSalesRoute: typeof SellerSalesRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerNotificationsRoute: SellerNotificationsRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerPerformanceRoute: SellerPerformanceRoute,
  SellerProfileRoute: SellerProfileRoute,
  SellerSalesRoute: SellerSalesRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  SellerRoute: SellerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
